// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Docusaurus generates a sidebar from the docs folder structure.
  // Ordering is controlled via `sidebar_position` frontmatter.
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

module.exports = sidebars;
